### PR TITLE
Add fixed debug messages

### PR DESCRIPTION
**Pull request by goulven04**
`DisplayUserMessage()` only supports type `char *`. So using `string` type to concatenate with `+` operator and then `c_str()` to convert back to `char *` is required.

### CODE REVIEW

**Comment by Flox06** [comment]
@goulven04 thx ! I'll give a try asap

**Comment by goulven04** [comment]
I was able to compile the DLL and make an actual test. Here is the output:
```
[23:51:12] [STANDS] CoFrance PlugIn: Scratchpad OK for LOT24S
[23:51:12] [STANDS] CoFrance PlugIn: Distance OK, Checking stand for LOT24S
[23:51:12] [STANDS] CoFrance PlugIn: Inserting LOT24S
[23:51:12] [STANDS] CoFrance PlugIn: Preparing API query
[23:51:12] [STANDS] CoFrance PlugIn: callsign: LOT24S
[23:51:12] [STANDS] CoFrance PlugIn: dep: EPKK
[23:51:12] [STANDS] CoFrance PlugIn: arr: LFMN
[23:51:12] [STANDS] CoFrance PlugIn: wtc: M
[23:51:12] [STANDS] CoFrance PlugIn: API Query didn't return 200 for LOT24S
```

Trying to mock the Euroscope call with `curl -X POST -d "callsign=LOT242S&dep=EPKK&arr=LFMN&wtc=M" https://fire-ops.ew.r.appspot.com/api/cfr/stand/query`, I get the following answer:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /api/cfr/stand/query</pre>
</body>
</html>
```

Looks like the API expect a GET instead of a POST: `curl -X GET "https://fire-ops.ew.r.appspot.com/api/cfr/stand/query?callsign=LOT242S&dep=EPKK&arr=LFMN&wtc=M"`:
```
[request]
code = 200
type = "success"
[data]
stand = "46A"%
```

Now, it's about deciding which side we want to change !

**Comment by pierr3** [comment]
@Flox06 totally forgot the API call was expecting a POST, sorry. If you can change that in the backend, everything should work fine on the plug-in side

**Comment by Flox06** [comment]
@goulven04 saved the game ! Thx 
I'll change the endpoint to handle POST cc @pierr3

**Comment by Flox06** [comment]
@goulven04 tested tonight, and it works as expected ! I think we can close this PR since we won't need to log this anymore (i hope)

BTW there is something a bit annoying in the actual implementation : IF the scratchpad is filled with a stand name, the system won't try anymore to query the server (which seems legit), BUT if we change the stand assignment server side, the scratchpad won't be updated automatically.
So the idea would to re-check periodically (ex: each 15 seconds ? or X radar refresh ?) by forcing the query to execute again, even if the scratchpad is set with stand name. 

cc @pierr3

**Pull request closed without merging**
